### ISSUE TITLE
Modules export

### ISSUE THREAD

**Issue by jochemvogel** [sjagoori/realtime-web#5]
https://github.com/sjagoori/realtime-web/blob/fa9b0d7f977e69126f6ec978750819b2958d40e9/modules/relatedCache.js#L26

Ik vind het zelf altijd wel mooier om het zo te doen:

```javascript
module.exports = {
    setCache,
    getCache
};
```

Dit zet ik dan onderaan ipv onder elke functie. Is voor twee functies misschien niet zo erg, maar je raakt snel het overzicht kwijt zodra je meer functies krijgt.

**Comment by sjagoori** [comment]
note: `exports.functionName = () => {}`
